### ISSUE TITLE
Dear Mr. atomic14, I look forward to your teaching

### ISSUE THREAD

**Issue by maoyanru** [atomic14/diy-alexa#18]
hi Dear Mr.atomic14
        Based on your suggestions, I learned to report issues on GitHub, thank you！！！
Now I have successfully imported your project into PlatfromIO, but an error occurred when I compiled the project (lib\tfmicro/tensorflow/lite/kernels/internal/min.h:29:10: error:'fmin' is not a member of'std'), the error screenshot is as follows:
![image](https://user-images.githubusercontent.com/23259959/119264988-b9a80c80-bc17-11eb-8b3c-0c3415c950bb.png)
In addition, my steps are also marked in the screenshots, I look forward to your guidance~think you！

**Comment by cgreening** [comment]
Hey - welcome to GitHub.

I've fixed the issues you had on the voice-controlled robot project - I think the error was already fixed in this commit - 5b8191b894a8acd220bf682d94ebdc008c6927f5.

Can you make sure you have the latest code:

```
git fetch
git pull
```

You may need to clear any changes you have locally.
