### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by AIchar** [atomic14/diy-alexa#2]
hi，
I got a compilation error and he showed

lib\tfmicro/tensorflow/lite/kernels/internal/max.h:29:10: error: 'fmax' is not a member of 'std'
lib\tfmicro/tensorflow/lite/kernels/internal/min.h:29:10: error: 'fmin' is not a member of 'std'

**Comment by cgreening** [comment]
Hi There,

I just checked on a fresh checkout from git and can't recreate. Can you tell me which version of platform.io you are using?

I'm using: PlatformIO, version 5.0.1

Thanks
Chris

**Comment by awal123** [comment]
Hi,

I had the same problem and found this solution (works for me): https://community.platformio.org/t/libraries-not-detected-cannot-open-source-file/16054/4

Best regards,
Artur

**Comment by AIchar** [comment]
Hi Chris,

The operating system I use is win10.
I'm using: PlatformIO IDE for VSCode, version 2.1.3
It seems to be the latest
![微信截图_20201028012013](https://user-images.githubusercontent.com/24260957/97337903-cd76d480-18bb-11eb-9bc8-17936cdd00f9.png)
![微信截图_20201028012033](https://user-images.githubusercontent.com/24260957/97337907-cea80180-18bb-11eb-8518-bbf48a5c069e.png)

Thanks
Arzhe

**Comment by cgreening** [comment]
Hi Arzhe,

I've tried adding a flag to the library.json to make the code use `std::max` instead of `std::fmax`. I'm not sure why this would work on my machine (a mac) and not windows.

Let me know if this fixes it.

Thanks
Chris

**Comment by AIchar** [comment]
> Hi Arzhe,
> 
> I've tried adding a flag to the library.json to make the code use `std::max` instead of `std::fmax`. I'm not sure why this would work on my machine (a mac) and not windows.
> 
> Can you pull the latest code and let me know if this fixes it.
> 
> Thanks
> Chris

The latest code still gets compilation errors.
But I added defined(arduino) to max.h and min.h to solve this problem.I can wake up esp32 through "Marven" now

**Comment by AIchar** [comment]
> Hi,
> 
> I had the same problem and found this solution (works for me): https://community.platformio.org/t/libraries-not-detected-cannot-open-source-file/16054/4
> 
> Best regards,
> Artur

Hi Artur,

It work for me too. I can compile it now

Thank
