### ISSUE TITLE
_mar_sounds_ Directory

### ISSUE THREAD

**Issue by ramainen** [atomic14/diy-alexa#21]
Can you write a few lines explanation about `_mar_sounds_` directory?

If I choosed custom word "dinosaur", can I just put into this folder amount of wavs like "dikobrauz", "dundellion", "dinoland", "bulbasaur" and so on? 
Are those files must be exactly 1 second * 16 kHz * 32 Bit?

**Comment by cgreening** [comment]
Yes, it's really for sounds that are confusing the detector, so you're examples are good.

All the files should be exactly 1 second @ 16kHz, **16 Bit.**
