### ISSUE TITLE
 i have a question regarding this alexa project

### ISSUE THREAD

**Issue by Anugaradhawa** [atomic14/diy-alexa#23]
I have a question regarding this project  (https://github.com/atomic14/diy-alexa ), how do I import background audio files to the jupyter notebook? plz reply for this questions

**Comment by cgreening** [comment]
Can you explain your question in a bit more detail? I'm not sure what it means.

**Comment by Anugaradhawa** [comment]
> Can you explain your question in a bit more detail? I'm not sure what it means.

ok first of all thanks for your reply I waiting for your reply for a long period, my first question is am I need to import background noises to Jupyter notebook friend?? I waiting for your quick reply

**Comment by cgreening** [comment]
I'm afraid I still don't really understand your question. There is background noise included in the command dataset that you can download as in the instructions in the notebook.

If you just want to run the project then the model is already trained and included in the firmware. You only need to train the model if you want to change the wake word.

```
Download data set
Download from: https://storage.cloud.google.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz - approx 2.3 GB

And then run

tar -xzf data_speech_commands_v0.02.tar.gz -C speech_data
```

**Comment by Anugaradhawa** [comment]
> I'm afraid I still don't really understand your question. There is background noise included in the command dataset that you can download as in the instructions in the notebook.
> 
> If you just want to run the project then the model is already trained and included in the firmware. You only need to train the model if you want to change the wake word.
> 
> ```
> Download data set
> Download from: https://storage.cloud.google.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz - approx 2.3 GB
> 
> And then run
> 
> tar -xzf data_speech_commands_v0.02.tar.gz -C speech_data
> ```

can you send your phone number, then I can send screenshots of errors in jupyter notebook friend . it's help for understand my question

**Comment by cgreening** [comment]
You can attach screenshots here. This is the best place to manage issues as it means everyone else can get value from the solutions. You can also copy and paste the errors from the jupyter notebook.

Are you trying to train the model on new data?

**Comment by Anugaradhawa** [comment]
ok friend

**Comment by Anugaradhawa** [comment]
now in my country10.37 pm, therefore I am going to sleep thanks for your replies I will be send my issues on tomorrow.

**Comment by Anugaradhawa** [comment]
> You can attach screenshots here. This is the best place to manage issues as it means everyone else can get value from the solutions. You can also copy and paste the errors from the jupyter notebook.
> 
> Are you trying to train the model on new data?

I try to train  model but it some errors

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/144692282-ac0dfb15-a63f-4098-b829-3f985f477855.png)
i try to generate training data but it says "FileNotFound" please tell me what I do for it

**Comment by cgreening** [comment]
If you want to train the model from scratch then you need to generate the training data by following the steps in the "Generate Training Data" notebook.

But as I said before, there is a fully trained model already in the firmware. You only need to train a new model if you want to have a new wake work.

**Comment by Anugaradhawa** [comment]
yes I want to make a new wake word

**Comment by Anugaradhawa** [comment]
> If you want to train the model from scratch then you need to generate the training data by following the steps in the "Generate Training Data" notebook.
> 
> But as I said before, there is a fully trained model already in the firmware. You only need to train a new model if you want to have a new wake work.

what notebook?? jupyter notebook ??

**Comment by cgreening** [comment]
Using a new wake word is a very advanced thing to try and do.

You will need to collect a lot of 1 second long samples of people saying your wake word and then regenerate the training data using the generate training data notebook.

**Comment by Anugaradhawa** [comment]
OK then I'll use the wake word you created

**Comment by Anugaradhawa** [comment]
am I need to use jupyter notebook for this project??

**Comment by cgreening** [comment]
If you just want to use the pre-trained model then you don't need to use the notebooks. You just need to build the firmware and run it on your ESP32.

**Comment by cgreening** [comment]
You will need to have some experience of using the esp32 with PlatformIO. If you have not done this before then try a few simple projects first.

**Comment by Anugaradhawa** [comment]
ok 

> You will need to have some experience of using the esp32 with PlatformIO. If you have not done this before then try a few simple projects first.

 I didn't use esp 32 before with platform.io, ok I will practice some projects using ESP 32 . where I found some tutorials??

**Comment by Anugaradhawa** [comment]
> If you just want to use the pre-trained model then you don't need to use the notebooks. You just need to build the firmware and run it on your ESP32.

how I build firmware for esp 32, Are you did some tutorials to make a firmware

**Comment by Anugaradhawa** [comment]
> If you just want to use the pre-trained model then you don't need to use the notebooks. You just need to build the firmware and run it on your ESP32.

can I use firmware that you create??

**Comment by cgreening** [comment]
This might be a good starting point: https://randomnerdtutorials.com/vs-code-platformio-ide-esp32-esp8266-arduino/

**Comment by Anugaradhawa** [comment]
> This might be a good starting point: https://randomnerdtutorials.com/vs-code-platformio-ide-esp32-esp8266-arduino/
![image](https://user-images.githubusercontent.com/94418247/144692282-ac0dfb15-a63f-4098-b829-3f985f477855.png)

ok thanks I will try this project on esp 32, but can you give a reason for this error??

**Comment by cgreening** [comment]
You haven't generated any training data so the files do not exist. If you want to train the model then you need to first run the notebook that generates the training data.

**Comment by Anugaradhawa** [comment]
> You haven't generated any training data so the files do not exist. If you want to train the model then you need to first run the notebook that generates the training data.

How i generate training data?? , Am i need background audio for making training data??

**Comment by cgreening** [comment]
Have you tried running the generate training data notebook and have followed the instructions in that notebook?

**Comment by Anugaradhawa** [comment]
> Have you tried running the generate training data notebook and have followed the instructions in that notebook?

what notebook?? I have tried to generate training data on jupyter notebook but it's come some errors

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/144729908-bf3b162b-3383-4308-84bc-7ba87f3bb2b8.png)

can you tell me what software you use in this picture ??? apple terminal or other software??

**Comment by cgreening** [comment]
This is just a command to play an audio file - you can use any command you want. The one I'm using is called `play` and comes as part of the operating system on the mac (and on Linux) as well.

You can use Audactity - https://www.audacityteam.org/ or whatever you have on windows. You can also install WSL (https://docs.microsoft.com/en-us/windows/wsl/install) on windows which will give you a Linux shell.

You are still trying to generate training data even though you said you didn't need to. I can't help you if you don't tell me what the errors are when you try and do it.

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/144692282-ac0dfb15-a63f-4098-b829-3f985f477855.png)

error is "FileNotFound"  what i do for this

**Comment by cgreening** [comment]
I've already explained this. You have not generated the training data. You need to run the notebook called: "Generate Training Data.ipynb"

**Comment by Anugaradhawa** [comment]
> I've already explained this. You have not generated the training data. You need to run the notebook called: "Generate Training Data.ipynb"

sorry sorry I forget it

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/144743249-3d3f6dc2-b97d-443b-a42b-5c7d87e7e734.png)

in this code part there have function names in "get_file" , That mean am I need to add some recorded background audio ??

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/144743759-d74ae118-490f-446a-86b7-a39fab0dce4b.png)


when I paste your curl command on command prompt in windows it's come "code": "no-auth", "error": "Bad auth, check token/params" what I do for this??

**Comment by cgreening** [comment]
On windows, you will need to change the single quotes to double quotes. But you also need to sign up with wit.ai and get your access token to replace the "XXX". 

In the instructions:

```
You can get the exact values for the Authorization header and the URL from the settings page of your Wit.ai application.
```

**Comment by cgreening** [comment]
If you can open new issues for problems you have that are specific to the issue you are facing it will be easier for people to help you. Give the issue a meaningful title and make sure you have followed the instructions.

**Comment by Anugaradhawa** [comment]
anyone not replies to my issue
