### ISSUE TITLE
Background audio files 

### ISSUE THREAD

**Issue by Anugaradhawa** [atomic14/diy-alexa#30]
> Ok, I think I understand what you are asking. There are samples of background noise included in the dataset that you download from here: https://storage.cloud.google.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz
> 
> Follow the instructions in the notebook and extract the file to the speech_data folder.

Ok tell me why are you use this background audio files??  For code or for training data ??

**Comment by Anugaradhawa** [comment]
ok i want to know are you use background audio files for training data??

**Comment by cgreening** [comment]
You want to train the neural network to detect your wake word. To do this it needs example audio files containing your wake word and example audio files that don't contain your wake word.

You also want it to be able to detect your wake word even when there is background noise. Or at least to be reasonably robust when there is background noise.

The background noise is used in the training of the neural network.

**Comment by Anugaradhawa** [comment]
> You want to train the neural network to detect your wake word. To do this it needs example audio files containing your wake word and example audio files that don't contain your wake word. These counter examples can be other words and background noise.
> 
> You also want it to be able to detect your wake word even when there is background noise. Or at least to be reasonably robust when there is background noise.
> 
> The background noise is used in the training of the neural network.

ok how i training the neural network ?? using a jupyter notebook??

**Comment by cgreening** [comment]
You can use the jupyter notebooks in the repository, but if you want to use different training data then you will need to modify the code.

There are some good tutorials on the TensorFlow website that you can use to learn how it all works, but you are in for a lot work!

https://www.tensorflow.org/overview

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/145405276-548275d5-c5c9-4d3a-9aab-64ad614fe8ed.png)


now I run the training data notebook but it'll occur an error "Processing problem noise" what is the reason??

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/145421718-5970d646-03b6-4181-8f1f-de8ca74ae3a6.png)


how do you add the audio sample to the training data??

**Comment by cgreening** [comment]
I recorded audio using my computer and built-in microphone to record additional background sounds.

You can comment out the lines that deal with the "mar" sounds if you don't need it.

**Comment by Anugaradhawa** [comment]
> I recorded audio using my computer and built-in microphone to record additional background sounds.
> 
> You can comment out the lines that deal with the "mar" sounds if you don't need it.

I ask how you add audio sample to the Jupyter noteboo

**Comment by cgreening** [comment]
I'm afraid the question doesn't make sense to me.

Are you asking how to read audio data into Python?

I think that you should follow some tutorials using jupyter notebook and tensorflow to learn more. The link I sent previously: https://www.tensorflow.org/overview is a good place to start.

There is also a good set of videos here: that will be very helpful for you to watch: https://www.youtube.com/playlist?list=PL-wATfeyAMNrtbkCNsLcpoAyBBRJZVlnf

**Comment by Anugaradhawa** [comment]
Ok i will watch the tutorial but i want to know how you add audio

**Comment by Anugaradhawa** [comment]
If you can't understand my question, let me know and I will try to explain my question a bit detail

**Comment by cgreening** [comment]
I don't understand your question.

**Comment by Anugaradhawa** [comment]
ok first tell me are you add audio samples to the jupyter notebook, I want answer in "yes" or "no" only

**Comment by Anugaradhawa** [comment]
> ok first tell me are you add audio samples to the jupyter notebook, I want answer in "yes" or "no" only

First answer this question , it's help you for understanding my idea

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/145405276-548275d5-c5c9-4d3a-9aab-64ad614fe8ed.png)


now I run the training data notebook but it'll occur an error "Processing problem noise" what is the reason??

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/145698529-c09057f4-2fda-402d-8012-66c8371f8de4.png)
 
How you add random sample of background??

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/145698565-8c45ec71-af95-4f6f-a5c5-32d938392ff1.png)
 
in your youtube vedio you tell " we also add in some random sample of background noise " I want to know only how you ass background samples ??

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/145699521-576c71b4-acad-4184-a75a-78815ff8c6d0.png)

Are we need to add this data_speech_commands folder to the notebook then it will run through all these samples and output files?

**Comment by Anugaradhawa** [comment]
Whya are you didn't response for my question ??

**Comment by upendramadhava** [comment]
> ![image](https://user-images.githubusercontent.com/94418247/145699521-576c71b4-acad-4184-a75a-78815ff8c6d0.png)
> 
> Are we need to add this data_speech_commands folder to the notebook then it will run through all these samples and output files?

I think you need to add command data file to the jupyter notebook friend

**Comment by upendramadhava** [comment]
> ![image](https://user-images.githubusercontent.com/94418247/145699521-576c71b4-acad-4184-a75a-78815ff8c6d0.png)
> 
> Are we need to add this data_speech_commands folder to the notebook then it will run through all these samples and output files?

I also have this question

**Comment by cgreening** [comment]
> Whya are you didn't response for my question 😔??

I have other things to do as well as support GitHub projects!

Some of your questions can be answered by reading and understanding the code in the notebook.

You download the speech commands dataset and uncompress it to the `speech_data` folder. Follow the instructions at the top of the notebook:

```
Download data set
Download from: https://storage.cloud.google.com/download.tensorflow.org/data/speech_commands_v0.02.tar.gz - approx 2.3 GB

And then run

tar -xzf data_speech_commands_v0.02.tar.gz -C speech_data
```

This will give you a folder containing a list of words along with sample audio for each word.

The code runs over the list of words and extracts features for each word. If the word is the wake word - in our case "marvin" then we repeat it multiple times so that we have a balanced data set - approximately an equal number of wake words examples vs non-wakeword examples.

I've added an additional folder to the `speech_data` folder with some background noise audio. Just create a folder in the `speech_data` folder called `_background_noise_` and put some recordings there of background noise.

If you don't have any background noise then comment out these lines:

```
for file_name in tqdm(get_files('_background_noise_'), desc="Processing Background Noise"):
    process_background(file_name, words.index("_background"))
```

The same is true for `_problem_noise_`. Create a folder called `_problem_noise_` in the speech data folder and put audio that seems to confuse the neural network there.

Once again if you don't have any problem noise samples then comment out these lines:

```
for file_name in tqdm(get_files("_problem_noise_"), desc="Processing problem noise"):
    process_problem_noise(file_name, words.index("_background"))
```

The same is the case for the `_mar_sounds_`. I recorded a bunch of words that sound like "marvin" to help the neural network ignore similar words.

Comment out these lines if you don't have these samples:

```
for file_name in tqdm(get_files("_mar_sounds_"), desc="Processing problem noise"):
    process_mar_sounds(file_name, words.index("_background"))
```

**Comment by Anugaradhawa** [comment]
> I have other things to do as well as support GitHub projects!

Ok i know 🙂 i was thinked you still can't understand my question

**Comment by Anugaradhawa** [comment]
> process_background(file_name

That's mean when i haven't background audio files then can i use this function "for file_name in tqdm(get_files('_background_noise_'), desc="Processing Background Noise"):
    process_background(file_name, words.index("_background"))"  ??

**Comment by Anugaradhawa** [comment]
> And then run
> 
> tar -xzf data_speech_commands_v0.02.tar.gz -C speech_data

Where i run this ?? on command prompt ??

**Comment by Anugaradhawa** [comment]
> If you don't have any background noise then comment out these lines:
> 
> ```
> for file_name in tqdm(get_files('_background_noise_'), desc="Processing Background Noise"):
>     process_background(file_name, words.index("_background"))
> ```
> 

When I have background files then how i add that background files to the code ??

**Comment by cgreening** [comment]
> > process_background(file_name
> 
> That's mean when i haven't background audio files then can i use this function " for file_name in tqdm(get_files('_background_noise_'), desc="Processing Background Noise"): process_background(file_name, words.index("_background")) " ??
> 
> > And then run
> > tar -xzf data_speech_commands_v0.02.tar.gz -C speech_data
> 
> Where i run this ?? on command prompt ??

You run this on the command prompt in the model folder. I don't think this will work in the normal windows command prompt. You would be better off installing WSL so that you have the full set of UNIX commands to work with.

**Comment by cgreening** [comment]
> _background_noise_

Put the 

> > If you don't have any background noise then comment out these lines:
> > ```
> > for file_name in tqdm(get_files('_background_noise_'), desc="Processing Background Noise"):
> >     process_background(file_name, words.index("_background"))
> > ```
> 
> When I have background files then how i add that background files to the code ??

Create a folder called `background_noise` in the `speech_data` folder and put the files there.

**Comment by Anugaradhawa** [comment]
> Create a folder called `background_noise` in the `speech_data` folder and put the files there.

ok thanks

**Comment by Anugaradhawa** [comment]
> > > process_background(file_name
> > 
> > 
> > That's mean when i haven't background audio files then can i use this function " for file_name in tqdm(get_files('_background_noise_'), desc="Processing Background Noise"): process_background(file_name, words.index("_background")) " ??
> > > And then run
> > > tar -xzf data_speech_commands_v0.02.tar.gz -C speech_data
> > 
> > 
> > Where i run this ?? on command prompt ??
> 
> You run this on the command prompt in the model folder. I don't think this will work in the normal windows command prompt. You would be better off installing WSL so that you have the full set of UNIX commands to work with.

ok

**Comment by Anugaradhawa** [comment]
> 

Are this step is essential for this project?? can I skip this step??

**Comment by Anugaradhawa** [comment]
> > _background_noise_
> 
> Put the
> 
> > > If you don't have any background noise then comment out these lines:
> > > ```
> > > for file_name in tqdm(get_files('_background_noise_'), desc="Processing Background Noise"):
> > >     process_background(file_name, words.index("_background"))
> > > ```
> > 
> > 
> > When I have background files then how i add that background files to the code ??
> 
> Create a folder called `background_noise` in the `speech_data` folder and put the files there.

Are this step is essential for this project?? can I skip this step??

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/145748158-a257ff71-cd0d-4404-b03d-0950bd02536c.png)


 I run this "Generate Training Data
" notebook but it's occur a error "Processing Background Noise:
0/0 [00:00<?, ?it/s]
0 0 0" what is the reason??

**Comment by Anugaradhawa** [comment]
> Create a folder called `background_noise` in the `speech_data` folder and put the files there.

**Comment by Anugaradhawa** [comment]
Why use this code "> > > ```
> > > for file_name in tqdm(get_files('_background_noise_'), desc="Processing Background Noise"):
> > >     process_background(file_name, words.index("_background"))"

**Comment by Anugaradhawa** [comment]
> > > _background_noise_
> > 
> > 
> > Put the
> > > > If you don't have any background noise then comment out these lines:
> > > > ```
> > > > for file_name in tqdm(get_files('_background_noise_'), desc="Processing Background Noise"):
> > > >     process_background(file_name, words.index("_background"))
> > > > ```
> > > 
> > > 
> > > When I have background files then how i add that background files to the code ??
> > 
> > 
> > Create a folder called `background_noise` in the `speech_data` folder and put the files there.
> 
> Are this step is essential for this project?? can I skip this step??

**Comment by upendramadhava** [comment]
> > > process_background(file_name
> > 
> > 
> > That's mean when i haven't background audio files then can i use this function " for file_name in tqdm(get_files('_background_noise_'), desc="Processing Background Noise"): process_background(file_name, words.index("_background")) " ??
> > > And then run
> > > tar -xzf data_speech_commands_v0.02.tar.gz -C speech_data
> > 
> > 
> > Where i run this ?? on command prompt ??
> 
> You run this on the command prompt in the model folder. I don't think this will work in the normal windows command prompt. You would be better off installing WSL so that you have the full set of UNIX commands to work with.

Yes it's not work correctly in Windows command prompt

**Comment by Anugaradhawa** [comment]
> Yes it's not work correctly in Windows command prompt,we can also use Ubuntu software on windows for this work

ok thanks friend

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/145773762-7631122e-a6ea-4e3f-8cdf-9b83855809e5.png)
your
![image](https://user-images.githubusercontent.com/94418247/145773790-6cc003b3-d8ff-42d1-8731-6f3f67372416.png)
my 
watch the differance of these screenshots

**Comment by cgreening** [comment]
Why do you think it is happening? I don't know what is happening on your machine you need to debug the code and work out what the problem is.

It seems likely that it can't find the audio files. Have you downloaded the speech data and extracted it? Is it in the right place? Where is the code looking for the files?

**Comment by Anugaradhawa** [comment]
> It seems likely that it can't find the audio files. Have you downloaded the speech data and extracted it? Is it in the right place? Where is the code looking for the files?

i also thinked that

**Comment by Anugaradhawa** [comment]
> Why do you think it is happening? I don't know what is happening on your machine you need to debug the code and work out what the problem is.
> 
> It seems likely that it can't find the audio files. Have you downloaded the speech data and extracted it? Is it in the right place?

I also think  it's can't find the audio files.yes i downloaded the speech data and extract in right click on zip file and extract it.i not place anywhere that file. I  just only download and extract it

**Comment by cgreening** [comment]
You need to create a folder called `speech_data` in the model folder (where you are running the notebooks) and copy the extracted files into that folder.

It expects to have all the words from the commands dataset under the `speech_data` folder.

**Comment by Anugaradhawa** [comment]
> (where you are running the notebooks) 
I only open a notebook in anaconda and run it normally

**Comment by Anugaradhawa** [comment]
> You need to create a folder called `speech_data` in the model folder (where you are running the notebooks) and copy the extracted files into that folder

How i copied speech data folder to model folder??

**Comment by Anugaradhawa** [comment]
I put the speech_data file to the model folder now it's working pretty thanks you solve my issue thank you

**Comment by Anugaradhawa** [comment]
I put the speech_data file to the model folder now it's working pretty thanks you solve my issue thank you
