### ISSUE TITLE
code (source code)

### ISSUE THREAD

**Issue by Anugaradhawa** [atomic14/diy-alexa#32]
why we need to  Generate Training Data in this project ??

**Comment by cgreening** [comment]
If you want to use the pre-trained model that has "Marvin" as the wake word then you don't need to.

You can just use the firmware from the firmware folder.

**Comment by cgreening** [comment]
Once you have generated the training data, you can train a neural network against it.

The trained neural network can then be exported to a C++ header file with all the weights. This is then used by the firmware that is running on the ESP32 to detect the wakeword.

Audio Files -> Training Data (features) -> Neural Network -> Export -> Firmware.
