### ISSUE TITLE
platform io (error)

### ISSUE THREAD

**Issue by Anugaradhawa** [atomic14/diy-alexa#34]
![image](https://user-images.githubusercontent.com/94418247/145926870-fffff0d7-8b0d-4b13-a6a0-e6973a62cf6e.png)

I install the visual studio code and download the platform io extension but its home page didn't open, I was waited nearly 30 minutes to open it. What's the reason you think ??

**Comment by cgreening** [comment]
Do you see any details of you follow the instructions where it says it failed?

You will probably be able to get help here: https://community.platformio.org

**Comment by Anugaradhawa** [comment]
> Do you see any details of you follow the instructions where it says it failed?
> 
> You will probably be able to get help here: https://community.platformio.org

Ok i will see tomorrow thanks

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/146116769-f5128319-8203-441f-af5e-939532e25012.png)


platformio not working

**Comment by cgreening** [comment]
Have you posted this problem on the platformio community to get support from them?

I suspect it is because you have spaces in your path (your windows username has spaces) which will break a lot of tools.

Check the platformio community and see if they have a suggestion for you.

**Comment by Anugaradhawa** [comment]
> I suspect it is because you have spaces in your path (your windows username has spaces) which will break a lot of tool

I will try to remove space between my username 👍🏻😊

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/146308640-cb02d1f3-5d8f-4d51-942a-a9446d22d15a.png)

Thanks, it's successfully installed but there is another error named "not found"

![image](https://user-images.githubusercontent.com/94418247/146309978-bfeb4fc9-a2d5-4bb5-a525-8d0ea64c1aca.png)

**Comment by Anugaradhawa** [comment]
thanks, you are a genius, it's working pretty now 
![image](https://user-images.githubusercontent.com/94418247/146504365-c1ed6bf7-33d9-401d-844d-9bb7b6dd6f6e.png)
![image](https://user-images.githubusercontent.com/94418247/146504383-7aeb244e-e5fa-4252-9dda-1976fdb14fa9.png)
I found the problem, the problem is not installed platformio correctly and I did not add python to the path when installed
