### ISSUE TITLE
Code functions

### ISSUE THREAD

**Issue by Anugaradhawa** [atomic14/diy-alexa#35]
![Screenshot_2021-12-14-21-06-52-82_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/94418247/146029712-3c3f584e-c5af-4318-a4c0-86cd0a159fc0.jpg)

I my previous issue you tell me to understand the code , therefore i open this issue for get some idea of functions in code . Ok tell me why are you use tf micro folder and src folder in this code??

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/146112453-6276f30d-c7ef-42d9-8c3d-b01edd0591d3.png)


why are you use this command "xxd -i converted_model.tflite > model_data.cc"

**Comment by cgreening** [comment]
Have you read the text in the screenshot you posted? It explains what this command is used for :)

Can you tell me which part of the text is unclear?

You need to convert the trained model into C code so that it can be embedded in the firmware and run on the ESP32.

I would like to think carefully on if this project is suitable for you. It is an advanced project that requires you to know python, machine learning and embedded development. I cannot teach you all of these things.

I would recommend that you just try and get the existing firmware working before you try and train a new wakeword.

**Comment by Anugaradhawa** [comment]
> I would recommend that you just try and get the existing firmware working before you try and train a new wake word

Ok thanks for your comment, I am 14 years old yet, therefore  i think i can not understand the code i have also study therefore mom limited the internet therefore i can't watch the long tutorials but leisure time i try projects using ESP 32.

**Comment by cgreening** [comment]
No problem - I will help where I can. But definitely getting platformio up and running and trying the existing firmware would be a good start.

**Comment by Anugaradhawa** [comment]
> No problem - I will help where I can. But definitely getting platformio up and running and trying the existing firmware would be a good start.

Where  i start to make a firmware , i haven't a idea.

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/146567642-6ddb3968-49bd-4f45-b65a-3d0b27fd7e6d.png)

I use an I2S microphone then am I need to remove analog microphones ADC code from the firmware folder??

**Comment by Anugaradhawa** [comment]
![image](https://user-images.githubusercontent.com/94418247/146567642-6ddb3968-49bd-4f45-b65a-3d0b27fd7e6d.png)

I use an I2S microphone then am I need to remove analog microphones ADC code from the firmware folder?? What programming language you used in this audio input file??

**Comment by cgreening** [comment]
This file contains all the configuration you should need - https://github.com/atomic14/diy-alexa/blob/master/firmware/src/config.h

You should not delete any code.

**Comment by Anugaradhawa** [comment]
> This file contains all the configuration you should need - https://github.com/atomic14/diy-alexa/blob/master/firmware/src/config.h
> 
> You should not delete any code.

Ok i understood
