### ISSUE TITLE
Input function

### ISSUE THREAD

**Issue by Anugaradhawa** [atomic14/diy-alexa#37]
![image](https://user-images.githubusercontent.com/94418247/146567642-6ddb3968-49bd-4f45-b65a-3d0b27fd7e6d.png)

I use an I2S microphone then am I need to remove analog microphones ADC code from the firmware folder?? What programming language you used in this audio input file??

**Comment by Anugaradhawa** [comment]
What programming language you used in this audio input folder ??

**Comment by cgreening** [comment]
Everything is controlled from this file: https://github.com/atomic14/diy-alexa/blob/master/firmware/src/config.h

You don't need to delete anything. Edit the config.h file for your hardware setup and then just use platformio to program your ESP32 board.

**Comment by Anugaradhawa** [comment]
> Everything is controlled from this file: https://github.com/atomic14/diy-alexa/blob/master/firmware/src/config.h
> 
> You don't need to delete anything. Edit the config.h file for your hardware setup and then just use platformio to program your ESP32 board.

Thanks
