### ISSUE TITLE
Code functions

### ISSUE THREAD

**Issue by Anugaradhawa** [atomic14/diy-alexa#38]
What programming language is you used  for made the audio input folder code?? Python or C++

**Comment by cgreening** [comment]
Do you mean the code that runs on the ESP32? That is C++.

**Comment by Anugaradhawa** [comment]
> Do you mean the code that runs on the ESP32? That is C++.

Ok thanks I thought it was python

**Comment by Anugaradhawa** [comment]
![IMG_20211222_060826](https://user-images.githubusercontent.com/94418247/147015519-ff09f616-1bc2-49d9-b3db-5a0fde155a02.jpg)
 

Why we use a ring buffer?? For what purpose??

**Comment by Anugaradhawa** [comment]
![IMG_20211222_060826](https://user-images.githubusercontent.com/94418247/147015519-ff09f616-1bc2-49d9-b3db-5a0fde155a02.jpg)

What purpose we need to used a ring buffer??

**Comment by cgreening** [comment]
We are keeping the latest 1 second worth of audio data samples. The ring buffer is an efficient way to store these sample without having to move them around in memory when more samples arrive.

**Comment by Anugaradhawa** [comment]
> We are keeping the latest 1 second worth of audio data samples. The ring buffer is an efficient way to store these sample without having to move them around in memory when more samples arrive.

Thanks, I understand. merry Christmas and Happy new year
