### ISSUE TITLE
DIY Alexa is not response 

### ISSUE THREAD

**Issue by Anugaradhawa** [atomic14/diy-alexa#51]
![image](https://user-images.githubusercontent.com/94418247/166147921-3bf050e7-6254-4559-aa52-88d8ef12a654.png)

I correctly upload the codes but it's doesn't show any response when I am saying  "Marvin" please help me I am waiting for your response I can't understand what is  the reason for this please help me

**Comment by cgreening** [comment]
The first thing to do is confirm that your microphone is working correclty.

This is a very simple Arduino sketch that will let you test this. Just update the code to match the pins you have connected the microphone to.

https://github.com/atomic14/esp32-i2s-mic-test/tree/main/i2s_mic_test

**Comment by Anugaradhawa** [comment]
> The first thing to do is confirm that your microphone is working correclty.
> 
> This is a very simple Arduino sketch that will let you test this. Just update the code to match the pins you have connected the microphone to.
> 
> https://github.com/atomic14/esp32-i2s-mic-test/tree/main/i2s_mic_test 

Yes i find the problem microphone is not working thanks your reply friend.i ordered another microphone i wait for come it . sorry i really forget to close this issue

**Comment by Anugaradhawa** [comment]
I have a issue . how you convert tf lite model into c code??

**Comment by Anugaradhawa** [comment]
![IMG_20220507_214334](https://user-images.githubusercontent.com/94418247/167262781-aba0e8cd-7db4-4b29-b9ba-45582060c0dd.jpg)

I have also another question . why you use "m_ " prefix in c code what it's purpose??

**Comment by cgreening** [comment]
It's a way to indicate to the reader that the variable is a member of the class.

https://stackoverflow.com/questions/1228161/why-use-prefixes-on-member-variables-in-c-classes/1229360#1229360

**Comment by Anugaradhawa** [comment]
> It's a way to indicate to the reader that the variable is a member of the class.
> 
> https://stackoverflow.com/questions/1228161/why-use-prefixes-on-member-variables-in-c-classes/1229360#1229360

Thanks friend
