### ISSUE TITLE
I CANT GET SOUND OUTPUT

### ISSUE THREAD

**Issue by lvzio** [atomic14/diy-alexa#52]
I biulded the projcet but i cant get voice output it takes the command like turns on the light but it cant create any sound to the speaker through I2S Amp
<img width="872" alt="Screenshot 2022-05-11 114026" src="https://user-images.githubusercontent.com/97988079/167819792-f7b82b96-344c-4d6c-8f42-8c094ea565ea.png">

**Comment by cgreening** [comment]
First thing to check would be that your I2S amplifier is wired up correctly. Does it work with a simple example?

**Comment by cgreening** [comment]
Also check that you've uploaded the file system.
