### ISSUE TITLE
Guru Meditation Error

### ISSUE THREAD

**Issue by acb18fl** [atomic14/diy-alexa#53]
Hi,
I can wake it up when I called 'marvin' and it makes the 'ting' sound, but it no longer responds to subsequent commands and gives Guru Meditation Error as shown in the pic. Any suggestions please?

<img width="889" alt="Screen Shot 2022-05-11 at 15 19 42" src="https://user-images.githubusercontent.com/79579126/167918706-551e3203-f9ff-4c03-9af1-67ae3d52638c.png">

**Comment by cgreening** [comment]
Looks like it's run out of memory. 

Lines 16-21 of NeuralNetwork.cpp

```
    m_tensor_arena = (uint8_t *)malloc(kArenaSize);
    if (!m_tensor_arena)
    {
        TF_LITE_REPORT_ERROR(m_error_reporter, "Could not allocate arena");
        return;
    }
```

We're really on the edge of what's possible with stock ESP32 devices. Does your device support PSRAM? If it does then enabling that and making it available for malloc would really help.

Alternatively we'll have to look for ways of reducing the amount of memory being used. One of the problems is that making an HTTPS request uses up a lot of memory that does not get returned.
