### ISSUE TITLE
Not an issue but more of a question on how to complie the code

### ISSUE THREAD

**Issue by dosipod** [atomic14/diy-alexa#56]
Hi , Would it be possible to include the steps to compile as we are not familiar with python . We can use VSC and pio on mac but could not find the info for beginners like us as we mainly use Arduino . We are working with students and this seems like a good project to also start with python  .  Thank you , we can  close this if that is not the correct place to ask

**Comment by cgreening** [comment]
Sorry for the delay in responding - I know it's more than a year!

The Python code is really just used to train the model and unless you want to train on a new wake work it's really just for information. The C++ code has the trained model baked into it so you can just use platformio to build and run.
